leave/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.home, name='home'),
	path('newPerson/', views.newPerson, name='newPerson'),
	path('person/', views.person, name='person'),
	path('newApplication/', views.newApplication, name='newApplication'),
	path('application/<int:application_id>', views.application, name='application'),
	path('status/<str:type>', views.status, name='status'),
	path('approve/<int:application_id>', views.approve, name='approve'),
	path('reject/<int:application_id>', views.reject, name='reject'),
	path('update/', views.update, name='update'),
	path('user/<int:user_id>', views.user, name='user'),
	path('users/', views.users, name='users'),
	path('error/', views.error, name='error'),
]

leave_manager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('leave.urls')),
	path('account/', include('accounts.urls')),
    path('account/', include('django.contrib.auth.urls')),
]

leave/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator, MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models.fields import SlugField

# Create your models here.

class Person(models.Model):
	DIRECTOR = 'DR'
	DEAN_OF_ACADEMIC_AFFAIRS = 'DOAA'
	DEAN_OF_FACULTY_AFFAIRS = 'DOFA'
	DEAN_OF_STUDENT_AFFAIRS = 'DOSA'
	HEAD_OF_DEPARTMENT = 'HOD'
	FACULTY = 'F'
	VISITING_FACULTY = 'VF'
	REGISTRAR = 'RG'
	HEAD_OF_STAFF = 'HOS'
	STAFF = 'S'

	COMPUTER_SCIENCE_AND_ENGINEERING = 'CSE' 
	ELECTRONICS_AND_COMMUNICATION_ENGINEERING = 'ECE'
	MECHANICAL_AND_MECHATRONICS_ENGINEERING = 'ME'
	HUMANITIES_AND_SOCIAL_SCIENCES = 'HSS' 
	MATHEMATICS = 'MH'
	PHYSICS = 'PH'
	NON_TEACHING_STAFF = 'NTS'

	PERSON_ROLES = (
		('DR', 'Director'),
		('DOAA', 'Dean of Academic Affairs'),
		('DOFA', 'Dean of Faculty Affairs'),
		('DOSA', 'Dean of Student Affairs'),
		('HOD', 'Head of Department'),
		('F', 'Faculty'),
		('VF', 'Visiting Faculty'),
		('RG', 'Registrar'),
		('HOS', 'Head of Staff'),
		('S', 'Staff'),
	)

	DEPARTMENT = (
		('CSE', 'Computer Science and Engineering'),
		('ECE', 'Electronics and Communication Engineering'),
		('ME', 'Mechanical and Mechatronics Engineering'),
		('HSS', 'Humanities and Social Sciences'),
		('MH', 'Mathematics'),
		('PH', 'Physics'),
		('NTS', 'Non Teaching Staff'),
	)

	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='person')

	faculty_id = models.CharField(max_length=10, blank=False, null=False, unique=True, default='0')
	leave_count = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(22)], blank=False, null=False, default=22)
	department = models.CharField(max_length=3, choices=DEPARTMENT, blank=False, null=False, default=COMPUTER_SCIENCE_AND_ENGINEERING)

	first_name = models.CharField(max_length=50, validators=[MinLengthValidator(1)], blank=False, null=False)
	last_name = models.CharField(max_length=50, blank=True, null=False)

	email = models.EmailField(blank=False, null=False, unique=True)
	office_no = models.IntegerField(blank=False, null=False, default='0000')

	role = models.CharField(max_length=5, choices=PERSON_ROLES, default='F')

	updated_at = models.DateTimeField(auto_now=True)
	created_at = models.DateTimeField(auto_now_add=True)

	# slug = models.SlugField(unique=True)

	class Meta:
		ordering = ['id']
		verbose_name = 'Person'
		verbose_name_plural = 'Persons'

	def is_director(self):
		return self.role == 'DR'

	def is_dean(self):
		return self.role == 'DN'

	def is_hod(self):
		return self.role == 'HOD'

	def is_valid(self):
		if self.email.split('@')[1] != 'lnmiit.ac.in':
			return False
		return len(self.first_name) > 0 and self.user is not None and self.leave_count >= 0

	def __str__(self):
		return f'{self.id}. {self.first_name} {self.last_name}'


class Application(models.Model):

	PENDING = 'P'
	APPROVED = 'A'
	REJECTED = 'R'

	APPLICATION_STATUS = (
		('P', 'Pending'),
		('A', 'Approved'),
		('R', 'Rejected'),
	)

	person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='applicant', default=1)
	status = models.CharField(max_length=1, choices=APPLICATION_STATUS, default='P')

	start_date = models.DateField(blank=False, null=False)
	end_date = models.DateField(blank=False, null=False)

	hasClasses = models.BooleanField(blank=False, null=False, default=False)
	rescheduled_date = models.DateField(blank=True, null=True)

	up_next = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='up_next', default=1)
	comments = models.TextField(blank=True, null=False)

	updated_at = models.DateTimeField(auto_now=True)
	created_at = models.DateTimeField(auto_now_add=True)

	# slug = models.SlugField(unique=True)

	class Meta:
		ordering = ['start_date', 'end_date']

	def is_valid(self):
		return (self.end_date - self.start_date) <= self.person.leave_count
		
	def __str__(self):
		return f'{self.id}. {self.person.first_name} {self.person.last_name} - {self.get_status_display()}'

leave/forms.py
import datetime

from django import forms
from django.contrib.auth.models import User

from .models import Application, Person


class UserForm(forms.ModelForm):

	class Meta:
		model = User
		fields = '__all__'
		# ['first_name', 'last_name', 'email', 'username', 'password']


class PersonForm(forms.ModelForm):

	class Meta:
		model = Person
		fields = '__all__'


class ApplicationForm(forms.ModelForm):

	start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
	end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

	rescheduled_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

	def clean(self):
		super(ApplicationForm, self).clean()

		start_date = self.cleaned_data.get('start_date')
		end_date = self.cleaned_data.get('end_date')
		rescheduled_date = self.cleaned_data.get('rescheduled_date')

		if start_date < datetime.date.now():
			raise forms.ValidationError('Invalid Input: Start Date must be > current date.')
		if end_date < datetime.date.now():
			raise forms.ValidationError('Invalid Input: End Date must be > current date.')
		if rescheduled_date < datetime.date.now():
			raise forms.ValidationError('Invalid Input: Rescheduled Date must be > current date.')
		if start_date > end_date:
			raise forms.ValidationError('Invalid Input: start date > end date')
		if (rescheduled_date >= start_date and rescheduled_date <= end_date):
			raise forms.ValidationError('Invalid Input: Rescheduled Date must not lie withing the leave dates.')
		
		return self.cleaned_data
	
	def save(self, commit=True):
		return super(ApplicationForm, self).save(commit=commit)

	class Meta:
		model = Application
		fields = ['start_date', 'end_date', 'hasClasses', 'rescheduled_date', 'comments']

leave/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls.base import reverse
from django.views.decorators.http import require_http_methods

from utils.utility import send_application_mail

from .forms import ApplicationForm, PersonForm, UserForm
from .models import Application, Person

# Create your views here.

def home(request):
	return render(request, 'leave/home.html', context={})


@login_required
@require_http_methods(["GET", "POST"])
def newPerson(request):
	person = PersonForm()
	if request.method == 'POST':
		person = PersonForm(request.POST)
		if person.is_valid():
			person.save()
			return render(request, 'leave/person.html', context={'form': person})
		else:
			return render(request, 'leave/newPerson.html', context={'form': person})
	return render(request, 'leave/newPerson.html', context={'form': person})


@login_required
@require_http_methods(["GET"])
def person(request):
	try:
		person = Person.objects.get(user_id=request.user.id)
		applications = Application.objects.filter(person=person)
		return render(request, 'leave/person.html', context={'person': person, 'applications': applications})
	except Person.DoesNotExist:
		messages.warning(request, 'Person does not exist.')
		return HttpResponseRedirect("../person")


@login_required
@require_http_methods(["GET", "POST"])
def newApplication(request):
	application = ApplicationForm()
	if request.method == 'POST':
		application = ApplicationForm(request.POST)
		if application.is_valid():
			try:
				application.save()
				person = Person.objects.get(pk=request.user.person.id)
				if Application.objects.filter(person=person).exists():
					application = Application.objects.filter(person=person).order_by('-created_at').first()
				if person.role in [Person.FACULTY, Person.VISITING_FACULTY]:
					try:
						up_next = Person.objects.get(department=person.department, role=Person.HEAD_OF_DEPARTMENT)
					except Person.DoesNotExist:
						up_next = person				
				else:
					try:
						up_next = Person.objects.get(role=Person.HEAD_OF_STAFF)
					except Person.DoesNotExist:
						up_next = person	
				application.person = person
				application.up_next = up_next
				application.save()
				send_application_mail(application)
				return HttpResponseRedirect(reverse('person', args=()))
			except Person.DoesNotExist:
				messages.error(request, f'Person does not exist.')
				return HttpResponseRedirect("../person")
		else:
			return render(request, 'leave/newApplication.html', context={'form': application})
	return render(request, 'leave/newApplication.html', context={'form': application})


@login_required
@require_http_methods(["GET"])
def application(request, application_id: int):
	try:
		application = Application.objects.get(pk=application_id)
		return render(request, 'leave/application.html', context={'application': application})
	except Application.DoesNotExist:
		messages.error(request, f'Application with id: {application_id} does not exist.')
		return HttpResponseRedirect("../status")


@login_required
@require_http_methods(["GET", "POST"])
def status(request, type: str):
	try:
		if type == "pending":
			applications = Application.objects.filter(up_next_id=request.user.person.id, status=Application.PENDING).order_by('-created_at')
		elif type == "approved":
			applications = Application.objects.filter(person__department=request.user.person.department, status=Application.APPROVED).order_by('-created_at')
		elif type == "rejected":
			applications = Application.objects.filter(person__department=request.user.person.department, status=Application.REJECTED).order_by('-created_at')
		return render(request, 'leave/status.html', context={'applications': applications, 'type': type})
	except Application.DoesNotExist:
		messages.error(request, f'Application does not exist.')
		return HttpResponseRedirect("../person")


@login_required
@require_http_methods(["GET", "POST"])
def approve(request, application_id: int):
	try:
		application = Application.objects.get(pk=application_id)
		try:
			if application.up_next.role == Person.HEAD_OF_STAFF:
				if Person.objects.filter(role=Person.REGISTRAR).exists():
					up_next = Person.objects.filter(role=Person.REGISTRAR).first()
				else:
					application.status = Application.REJECTED
					up_next = request.user.person
			elif application.up_next.role == Person.REGISTRAR:
				application.status = Application.APPROVED
				person = Person.objects.get(pk=application.person.id)
				up_next = person
			elif application.up_next.role == Person.HEAD_OF_DEPARTMENT:
				if Person.objects.filter(role=Person.DEAN_OF_FACULTY_AFFAIRS).exists():
					up_next = Person.objects.filter(role=Person.DEAN_OF_FACULTY_AFFAIRS).first()
				else:
					application.status = Application.REJECTED
					up_next = request.user.person
			elif application.up_next.role == Person.DEAN_OF_FACULTY_AFFAIRS:
				if Person.objects.filter(role=Person.DIRECTOR).exists():
					up_next = Person.objects.filter(role=Person.DIRECTOR).first()
				else:
					application.status = Application.REJECTED
					up_next = request.user.person
			elif application.up_next.role == Person.DIRECTOR:
				application.status = Application.APPROVED
				person = Person.objects.get(pk=application.person.id)
				up_next = person
			else:
				messages.error(request, 'Error in approving application.')
				return HttpResponseRedirect("../status")
			application.up_next = up_next
			application.save()
			send_application_mail(application)
			return HttpResponseRedirect(reverse('status', args=()))
		except Person.DoesNotExist:
			messages.error(request, "Person does not exist")
			return HttpResponseRedirect("../status")
	except Application.DoesNotExist:
		messages.error(request, f'Application with id: {application_id} does not exist.')
		return HttpResponseRedirect("../status")

@login_required
def reject(request, application_id: int):
	try:
		application = Application.objects.get(pk=application_id)
		application.status = Application.REJECTED
		application.save()
		send_application_mail(application)
		return HttpResponseRedirect(reverse('status', args=()))
	except Application.DoesNotExist:
		messages.error(request, f'Application with id: {application_id} does not exist.')
		return HttpResponseRedirect("../status")


@login_required
def update(request):
	try:
		form = UserForm()
		if request.POST:
			if form.is_valid():
				form.save()
				return HttpResponseRedirect(reverse('user', args=(request.user.id, )))
			else:
				return render(request, 'leave/user.html', context={'form': form})
		return HttpResponseRedirect(reverse('user', args=(request.user.id, )))
	except Exception as e:
		messages.error(request, str(e))
		return HttpResponseRedirect("../home")


@login_required
def user(request, user_id):
	try:
		user = User.objects.get(pk=user_id)
		return render(request, 'leave/user.html', context={"user": user})
	except User.DoesNotExist:
		messages.error(request, "User Doesn't Exist")
		return HttpResponseRedirect("../home")


@login_required
def users(request):
	users = User.objects.all()
	return render(request, 'leave/users.html', context={'users': users})


@login_required
def error(request):
	return render(request, 'leave/error.html', context={"message": "Error test.", "type": "Type Error", "link": "home"})

leave/templates/leave/application.html
<!-- "templates/leave/application.html" -->
{% extends "leave/base.html" %}

{% block title %}
	Application {{ application.id }}
{% endblock %}

{% block head %}
	{% load static %}
	{% load bootstrap4 %}
	{% load fontawesome_5 %}
	{% load humanizelib %}
{% endblock %}

{% block body %}
	<div class="container-fluid text-center">
		<div class="row justify-content-center">
			<div class="col-md-4">
				<img src="https://img.icons8.com/bubbles/200/000000/multi-edit.png" />
			</div>
			<div class="col-md-8 application">
				<div id="printableArea" class="application__grid">
					<h2 class="application__grid__name">{{ application.person.first_name }} {{ application.person.last_name }}</h2>
					<div class="row application__grid__date">
						<div class="col-md-6">From: {{ application.start_date|date }}</div>
						<div class="col-md-6">To: {{ application.end_date|date }}</div>
					</div>
					<div class="row application__grid__desc">
						<div class="col-md-4">Status: <span class="alert-{% if application.status == 'A' %}success{% elif application.status == 'P' %}warning{% else %}danger{% endif %}">{{ application.get_status_display }}</span></div>
						<div class="col-md-3">Has Classes: {{ application.hasClasses }}</div>
						<div class="col-md-5">Rescheduled Class: {{ application.rescheduled_date }}</div>
					</div>
					<div style="float:left; margin:2rem;">Comments:</div>
					<div class="application__grid__comments"> {{ application.comments }}</div>
					{% if application.status == 'P' %}
						<div class="application__grid__up_next">To be approved by: {{ application.up_next.get_role_display }}</div>
					{% endif %}
					<div class="row mt-0 mb-0">
						<div class="col-md-6">
							<p class="text-left pt-0 pr-auto pb-1 pl-1"><small class="text-muted">Last Updated {{ application.updated_at|naturaltime }}</small></p>
						</div>
						<div class="col-md-6">
							<p class="text-right pt-0 pr-1 pb-1 pl-auto"><small class="text-muted">Added {{ application.created_at|naturaltime }}</small></p>
						</div>
					</div>
				</div>
				<button onclick="printDiv('printableArea')" class="form-control form-control-lg btn btn-outline-warning btn-lg mt-3" type="submit" name="button">Print</button>
			</div>
		</div>
	</div>
	<script>
		function printDiv(divName) {
			var printContents = document.getElementById(divName).innerHTML;
			var originalContents = document.body.innerHTML;

			document.body.innerHTML = printContents;

			window.print();

			document.body.innerHTML = originalContents;
		};
	</script>
{% endblock %}

leave/templates/leave/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

	<!-- Font Icons -->
	<script src="https://kit.fontawesome.com/3288abfe00.js" crossorigin="anonymous"></script>
	
	<!-- CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
		integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
		crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
		crossorigin="anonymous">
	
	<!-- JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
		integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
		crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
		integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
		crossorigin="anonymous"></script>

	{% load static %}

	<link href="{% static 'leave/css/style.css' %}" rel="stylesheet" />


	<script rel="javascript" href="{% static 'leave/js/script.js' %}"></script>

	{% block head %}{% endblock %}
	
	<!-- Icon -->
	<link rel="icon" href="https://img.icons8.com/ultraviolet/64/000000/xbox-b.png" />
	<title> {% block title %}{% endblock %} | LNMIIT LMS</title>
</head>
<body>
	<!--TODO: Add NavBar with: App Name, LogIn, LogOut, Register, etc-->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #0a192f; border-bottom: .125rem solid #ccd6f6;">
        <a class="navbar-brand" href="{% url 'home' %}" style="color: #c2dde6; font-size: 2rem;">LMS LNMIIT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="background-color: #c2dde6;">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-size: 1.1rem;">
            <ul class="navbar-nav mr-3 ml-auto">
				{% if request.user.id == 1 %}
					<li class="nav-item dropdown">
						<div class="nav-link dropdown-toggle" style="color: #c2dde6;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Super">
							Admin
						</div>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" role="menu">
							<a class="dropdown-item" href="{% url 'admin:index' %}">Admin Site</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'newPerson' %}">Add Person</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'users' %}">Users</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'error' %}">Error</a>
						</div>
					</li>
				{% endif %}
				{% if user.is_authenticated %}
					<li class="nav-item dropdown">
						<div class="nav-link dropdown-toggle" style="color: #c2dde6;" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Profile">
							Profile
						</div>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" role="menu">
							<a class="dropdown-item" href="{% url 'person' %}">Details</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'newApplication' %}">New Application</a>
							<div class="dropdown-divider"></div>
							{% if request.user.person.role != 'S' and request.user.person.role != 'F' and request.user.person.role != 'VF' %}
								<a class="dropdown-item" href="{% url 'status' 'pending' %}">Pending</a>
								<!-- <a class="dropdown-item" href="{% url 'status' 'up-coming' %}">Up-coming</a> -->
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" href="{% url 'status' 'approved' %}">Approved</a>
								<a class="dropdown-item" href="{% url 'status' 'rejected' %}">Rejected</a>
								<div class="dropdown-divider"></div>
							{% endif %}
							<a class="dropdown-item" href="https://www.lnmiit.ac.in/uploaded_files/2%20-%20HR%20Manual.pdf" target="_blank">HR - Manual</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'password_reset' %}">Reset password</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'logout' %}">Sign out</a>
						</div>
					</li>
				{% else %}
					<li class="nav-item" >
						<a class="nav-link" style="color: #c2dde6;" href="{% url 'login' %}" title="Login">
							Log In
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" style="color: #c2dde6;" href="{% url 'signup' %}">
							Register
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" style="color: #c2dde6;" href="{% url 'password_reset' %}" title="Reset password">
							Reset Password
						</a>
					</li>
				{% endif %}
				{% if user.is_superuser %}
					<li class="nav-item">
						<a class="nav-link" style="color: #c2dde6;" href="{% url 'signup' %}">
							Register
						</a>
					</li>
				{% endif %}
            </ul>
        </div>
    </nav>

	{% if messages %}
		{% for message in messages %}
			<div class="container-fluid p-0">
				<div class="alert {{ message.tags }} alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} text-center" role="alert">
						{{ message }}
					</div>
				</div>
			</div>
		{% endfor %}
	{% endif %}

    {% block body %}{% endblock %}

    <!-- <hr class="mt-4"> -->
    
    <!-- Comments and Suggestions -->
    <!-- <section class="comments">
        <script src="https://utteranc.es/client.js" repo="PriyanshBordia/LNMIIT-Leave-Management" issue-term="title"
            label="utteranc.es" theme="dark-blue" crossorigin="anonymous" async>
		</script>
    </section> -->

	<!-- Footer Section -->
	<footer class="footer">
		<div class="footer__grid">
			<div class="footer__grid__handles">
				<a href="https://github.com/PriyanshBordia/LNMIIT-Leave-Management" target="_blank" title="Repository"><i class="fab fa-github"></i></a>
				<a href="mailto:19ucs257@lnmiit.ac.in" target="_blank" title="Priyansh Bordia"><i class="fas fa-envelope"></i></a>
			</div>
			<div class="footer__grid__text">
				<span class="has-hover">Created by Priyansh Bordia &copy; 2021.</span>
			</div>
		</div>
	</footer>
</body>
</html>

leave/templates/leave/person.html
<!-- "templates/leave/person.html" -->
{% extends "leave/base.html" %}

{% block title %}
	Person
{% endblock %}

{% block head %}
	{% load static %}
	{% load bootstrap4 %}
	{% load fontawesome_5 %}
	{% load humanizelib %}
{% endblock %}

{% block body %}
	<div class="person">
		<div class="row">
			<div class="col-md-4">
				<div class="person__grid">
					<img src="https://img.icons8.com/bubbles/200/000000/iphone-spinner.png" />
					<p class="person__grid__name">{{ person.first_name }} {{ person.last_name }}</p>
					<p class="person__grid__username">{{ request.user.username }} </p>
					<p class="person__grid__email"><i class="fas fa-envelope"></i> {{ person.email }} </p>
					<span>
						<p class="person__grid__department"><i class="fas fa-envelope"></i> {{ person.get_department_display }} </p>
						<p class="person__grid__office_no">Office No.</i> {{ person.office_no }} </p>
					</span>
					<p class="person__grid__leave_count">Leave Count: </i> {{ person.leave_count }}</p>
					<p class="person__grid__faculty_id">Employee Id: </i> {{ person.faculty_id }} </p>
				</div>
			</div>
			<div class="col-md-8">
				{% if applications|length > 0 %}
					<div class="person__grid__application">
						<table class="center">
							<thead>
								<tr>
									<th>UAID</th>
									<th>Start Date</th>
									<th>End Date</th>
									<th>Status</th>
									<th>Details</th>
								<tr>
							</thead>
							<tbody>
								{% for application in applications %}
									<tr>
										<td>{{ application.id }}</td>
										<td>{{ application.start_date }}</td>
										<td>{{ application.end_date }}</td>
										<td>{{ application.get_status_display }}</td>
										<td><a class="form-control form-control-lg btn btn-outline-info btn-lg " href="{% url 'application' application.id %}" role="button">Show</a></td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				{% else %}
					<div class="row">
						<div class="alert alert-info" role="alert">No Application.</div>
					</div>
					<div class="row">
						<div class="col-md-2"></div>
						<div class="col-md-8">
							<a class="form-control form-control-lg btn btn-outline-success btn-lg " href="{% url 'newApplication' %}" role="button">Apply</a>
						</div>
						<div class="col-md-2"></div>
					</div>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

<!-- <div class="row mt-0 mb-0 pb-0">
	<div class="col-md-8 pb-0">
		<p class="text-left pt-auto pr-auto pb-0 pl-1"><small class="text-muted">Last Updated
				{{ person.updated_at|naturaltime }}</small></p>
	</div>
	<div class="col-md-4 pb-0">
		<p class="text-right pr-1 pt-0 pb-0 pl-auto"><small
				class="text-muted">{{ person.created_at|naturaltime }}</small></p>
	</div>
</div> -->

leave/templates/leave/template.html
<!-- "templates/leave/**.html" -->
{% extends "leave/base.html" %}

{% block title %}

{% endblock %}

{% block head %}
	{% load static %}
	{% load bootstrap4 %}
	{% load fontawesome_5 %}
	{% load humanizelib %}
{% endblock %}

{% block body %}

{% endblock %}